### ISSUE TITLE
11.1.1 update has almost no functionality

### ISSUE THREAD

**Issue by emergere** [haxor-music/hxr-jam-live-11-public#11]
what's new?
The latest update may have broken the scripting or something. It isn't working. I checked NI forum but nothing there about it. Plugged in the launchpad s and seems to work except for mix volume. Just saying. Don't know enough about scripting to know if it's me or the script. Also just trying it out on Mac m1 for the first time and updated live 11.1 before seeing if it worked. It was mostly working on the PC I was using but I got rid of it. Il'll try another pc tomorrow. and I'm rambling.

**Comment by haxor-music** [comment]
Thanks for the report!

I will try to find time check the latest Live version and see what is causing the issue. Honestly - I've not hurried to update to 11.1 since most of the NI plugins are not working with M1 yet. But I will try to fix this still during this week!

**Comment by haxor-music** [comment]
Hi - I just tried with both 11.1.1 and 11.1.5beta on OSX and both of those seems to work on quick testing after you copied the scripts from the release zip (both HXR_JAM + _NativeInstruments folders) into the MIDI Remote Scripts folder under the new Live 11.1.
Note: I was running it under Rosetta since most of the NI plugins are still not M1 compatible...

**Comment by emergere** [comment]
Hi, Did rosetta and checked that all python was correct. I think the issue was/is controller editor or Maschine 3 MIDI mode. When I looked the Template had changed to default. Loaded the correct template again and some of it works. ClipSlots trigger clips work but don't light. No Step mode or pad mode etc. Turned off Maschine 3 midi mode and clip slot mode starts working. Maybe the order in which the Maschines are started? For now it is working. The wrong template was the original problem. appreciate the help.

**Comment by haxor-music** [comment]
Closing as this is resolved.
